version: '3'
services:
  node-builder-web:
    image: node:16.14.0
    volumes:
      - ./:/var/www/html
    container_name: node-builder-web
    command: >
      bash -c "cd /var/www/html && yarn install"

  fe-template:
    depends_on:
      - node-builder-web
    image: nginx
    ports:
      - '8080:80'
    restart: always
    volumes:
      - ./config/nginx-custom.conf:/etc/nginx/conf.d/default.conf
      - ./config/mime.types:/etc/nginx/mime.types
      - ./dist:/usr/share/nginx/html
    container_name: fe-template
    networks:
      - fe-template

networks:
  busk-web:
    driver: bridge